//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Greekapi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Card
    {
        public string cardid { get; set; }
        public string cardholdername { get; set; }
        public string cardbin { get; set; }
        public string carddate { get; set; }
        public string cardnumber { get; set; }
    }
}
