//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Greekapi
{
    using System;
    using System.Collections.Generic;
    
    public partial class credential
    {
        public string id { get; set; }
        public string userid { get; set; }
        public string password { get; set; }

        public static credential SetCredential(string Userid, string Password)
        {
            credential credential_ = new credential()
            {
                id = Guid.NewGuid().ToString().Remove('-'),
                password = Password,
                userid = Userid
            };
            return credential_;
        }
    }
}
