//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Greekapi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public string userid { get; set; }
        public string emailaddress { get; set; }
        public string msisdn { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string age { get; set; }
        public string physicaladdress { get; set; }
        public static Customer SetCustomer(string email, string firstname, string lastname, string cellnumber, string age, string paddress)
        {
            Customer customer = new Customer()
            {

            }
        }
    }
}
