//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Greekapi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deliveri
    {
        public string id { get; set; }
        public string email { get; set; }
        public string msisdn { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string platenumber { get; set; }
        public string delivermodetype { get; set; }
        public string licensenumber { get; set; }
    }
}
