//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Greekapi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public string itemid { get; set; }
        public string itemdescription { get; set; }
        public string itemvalue { get; set; }
        public string salestatus { get; set; }
        public string userid { get; set; }
        public string isonsale { get; set; }
    }
}
