//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Greekapi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public string transactionid { get; set; }
        public string transactionitem { get; set; }
        public string transactionuser { get; set; }
        public string transactionsalestatus { get; set; }
        public string otpstatus { get; set; }
        public System.DateTime timelogged { get; set; }
    }
}
